"""
Optical centering for icons.

For each icon PNG, compares the center of its bounding box with its visual weight
center (alpha-weighted centroid) and writes CSS that nudges the icon so it *looks*
centered inside buttons and slots. Only part of the difference is applied (STRENGTH),
because full correction overshoots.

Usage: python3 tools/icon_offsets.py super-casual/kit/assets super-casual/kit/assets/offsets.css
"""
import os, sys
import numpy as np
from PIL import Image

STRENGTH = 0.6
src, out = sys.argv[1], sys.argv[2]
lines = ['/* Generated by tools/icon_offsets.py — optical centering nudges (percent of icon size) */']
for f in sorted(os.listdir(src)):
    if not f.endswith('.png'):
        continue
    a = np.array(Image.open(os.path.join(src, f)).convert('RGBA'))[..., 3].astype(float)
    h, w = a.shape
    ys, xs = np.mgrid[0:h, 0:w]
    cx, cy = (a * xs).sum() / a.sum(), (a * ys).sum() / a.sum()
    ox = (w / 2 - cx) / w * 100 * STRENGTH
    oy = (h / 2 - cy) / h * 100 * STRENGTH
    if abs(ox) < 0.5 and abs(oy) < 0.5:
        continue
    lines.append(f'img[src$="/{f}"] {{ --ox:{ox:.1f}%; --oy:{oy:.1f}%; }}')
    print(f'{f:18} x {ox:+.1f}%  y {oy:+.1f}%')
open(out, 'w').write('\n'.join(lines) + '\n')
